baseURL: https://glacierzero.com
languageCode: en-us
title: GlacierZero
paginate: 5
theme: "PaperMod"

buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
publishDir: "docs"

menu:
  main:
    - identifier: about
      name: About me
      url: about/
      weight: 1
    - identifier: tags
      name: Tags
      url: tags/
      weight: 2
    - identifier: archive
      name: Archive
      url: archive/
      weight: 3
    - identifier: search
      name: Search
      url: search/
      weight: 4

params:
  description: "My personal site"
  author: Plácido Fernández Declara
  keywords: ["c++", "python", "guides", "open-source", "programming", "software"]
  images: ["/logo-banner.png"]
  dateFormat: "2 January 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowCodeCopyButtons: false
  ShowFullTextInRSS: true
  ShowShareButtons: false
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  comments: false
  # hidemeta: false
  # hideSummary: false

  homeInfoParams:
    LogoLight: /logo-light-theme.jpg
    # LogoDark: /logo-dark-theme.jpg
    Content: >
      My personal site


      *Written by Placido Fernandez Declara*
  socialIcons:
    - name: github
      url: "https://github.com/fdplacido"
    - name: gitlab
      url: "https://gitlab.cern.ch/plfernan"
    - name: twitter
      url: "https://twitter.com/fdplacido"
    - name: rss
      url: "https://glacierzero.com/index.xml"

social:
  twitter: glacierzero

minify:
    disableXML: true
    minifyOutput: true

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for the search

taxonomies:
  tag: tags
  series: series
